nullworks/cathook

- src/hacks/AntiAim.cpp
J_Tanzanite: Here is a suggestion which I sorta have been asking for a while now - fix aa yaw! Right now if you say, set it to 90, it doesn't go +90 degrees from where you are looking, would be nice to get that implemented.
J_Tanzanite: makes hvhs much better
boots: @J_Tanzanite basically just have it so that there's a "keep + static" option that keeps your yaw but also adds the static value to it?
J_Tanzanite: Yes
J_Tanzanite: NCC has that and it is godf*\@\sKing useful
> Add offset keep

- makefile
dunno if we need to use sh -c for "||" but it works so who cares
> Use g++ if g++-6 doesn't exist (closes #29)

- src/gui/ncc/Menu.cpp
You added it but it should be in the menu for ease of use.
> Added cvar to respect vaccinator to menu

- src/hacks/Aimbot.cpp
- src/hacks/AntiAim.cpp
- src/playerlist.cpp
I added more checks so the aimbot knows when it can bodyshot instead of aiming for the head as well as making auto-closest choose a center hit box over closest to crosshair.
Bodyshotting over headshotting improves chance to hit due to the body being a bigger hitbox.
I also added my own steam ids to the developer list
> Improved bodyshot detection and Auto-Closest

- src/gui/ncc/Menu.cpp
- src/hacks/Aimbot.cpp
- src/hacks/AutoSticky.cpp
I created a simple vis check to auto-sticky to prevent it detonating on people behind walls. While looking through aimbot.cpp i saw a todo to add smg to the list of should aim blacklist weapons so i went ahead and did that. having the smg in the list is nice as it doesnt stop while reloading.
> Added sticky vis check 

- attach
- attach-backtrace
we already run `sudo ./detach` so i have no clue why we don't `sudo gdb` :thinking:
> use sudo with gdb

- attach-pid
Now if you do not provide a PID, it will automagically find whatever game Steam is running.
Nobody except for maybe 2 people are going to use this, but I thought it was nice.
> Add auto-detection to ./attach-pid

- README.md
Before: gcc6 is installed, then script updates to gcc7.
Now: other dependencies are installed first, then gcc6 downgrade. In no way should the script install gcc7 now.
> Remove redundant installation + fix accidental update

- README.md
The current installation script requires 3 user interactions:
1. Password for sudo
2. base-devel "select packages"
3. gcc in conflict with gcc-mutilibs.
Fix for 1 could be to use yaourt instead. 
Fix for 2 would be to manually install the packages inside the group - but which ones are quired for cathook compilation?
Fix for 3 is to use --noconfirm.
On second thought, would base-devel even be required? It's basically the first thing ever installed on arch machines. And the conflic with gcc and gcc-multilibs is because base-devel installs gcc.
Removing base-devel would fix 2.
After testing the script, using --noconfirm to fix 3 auto-no's. But, using "yes | " before the script auto-yes's. 
tl;dr Removed base-devel from installation, since it's more than likely already installed. Auto-confirm …
> Removed redundancies & user interaction.

- README.md
Edit: Proper title would be "Cathook installation script running update-menu (removed) instead of update-data
```
Building cathook
make[1]: Leaving directory '/home/depre/cathook'
bash: update-menu: No such file or directory
```
update-menu was renamed to update-data recently.
> bash: update-menu: No such file or directory

- make-nogui.sh
https://github.com/koalaman/shellcheck/wiki/SC2148
Different shells support different features. To give effective advice, ShellCheck needs to know which shell your script is going to run on. You will get a different numbers of warnings about different things depending on your target shell.
ShellCheck normally determines your target shell from the shebang (having e.g. #!/bin/sh as the first line). The shell can also be specified from the CLI with -s, e.g. shellcheck -s sh file.
If you don't specify shebang nor -s, ShellCheck gives this message and proceeds with some default (bash).
Note that this error can not be ignored with a [[directive]]. It is not a suggestion to improve your script, but a warning that ShellCheck lacks information it needs to be helpful.
> Tips depend on target shell and yours is unknown. Add a shebang.

- README.md
- generate-class-headers.js
- generate-dummy-header.js
- generate-dynamic-header.js
JavaScript allows you to define strings in one of three ways: double quotes, single quotes, and backticks (as of ECMAScript 6). Each of these lines creates a string and, in some cases, can be used interchangeably. The choice of how to define strings in a codebase is a stylistic one outside of template literals (which allow embedded of expressions to be interpreted). Many codebases require strings to be defined in a consistent manner. This rule takes as parameter the style you prefer ("double", "single" or "backtick") default is double.
```
//Bad with double:
var single = 'single';
var unescaped = 'a string containing "double" quotes';
```
Also I was gonna add codacy button but decided against it, then realised I have no idea how to un-commit shit so I just made more commits fixing it or …
> Strings must use doublequote. (quotes)

- README.md
Before: Script fails with `fatal error: GL/glew.h:  No such file or directory #include <GL/glew.h>`
After: Everything works.
> Added glew to arch dependencies

- update-gccdowngrade
EDIT: Updated to make codacity happy. I borked shit last time.
This should only be useful for arch users who can not install gcc6 and gcc7 as seperate packages due to either lack of knowledge or technical reasons.
I, personally, am unable to use the downgrader package to install a separate instance of gcc without breaking the fuck out of my graphics card (???) and steam.
What this does:
Downgrades to gcc6
Update cathook
Upgrades back to gcc7
What this does NOT do:
Install gcc6 as a separate package
Download gcc6/gcc7 if they're missing
> Patch for arch users to update cathook by downgrading gcc first, then re-udpating gcc.

- include/copypasted/CSignature.h
- include/hooks.hpp
- include/hooks/hookedmethods.hpp
- include/hooks/others.hpp
- include/interfaces.hpp
- include/offsets.hpp
- src/copypasted/CSignature.cpp
- src/hack.cpp
- src/hooks.cpp
- src/hooks/others.cpp
- src/interfaces.cpp
- Fixed 100% rare medal flip by replacing the unused byte patch with a hook.
- Added CatVar `cat_medal_flip`
- Added pattern scanning for `libvstdlib.so`
> Fixed 100% Rare Medal Flip

- data/menu.json
- src/hacks/Backtrack.cpp
- src/visual/menu/ncc/Menu.cpp
I don't think backtrack should be enabled by default since it makes for a bad user experience in my opinion. For example: 
- It creates annoying dots that don't go away in some occasions
- It lags the game out if aimbot is used in conjunction with backtrack (?)
- There is no GUI option to disable it
> Disable backtrack by default and add UI setting

- install-all
- tools/README
- tools/attach
- tools/update
- tools/updater
- tools/updater.sh
The goal of this pull-request is to make updating cathook in the future as easy as possible. This pull-request is backwards compatible with previous versions of cathook (as in: It won't break them), but a reinstall(using the install script) is required in order to enable the new update script.
^ This is what the cathook folder will look like after the install. Scripts located in this folder can be updated and added by using the `tools` folder located in nullworks/cathook.
**Update Script**
The `update` script first downloads the latest version of the `updater.sh` script using wget. This ensures that the user will always have the up to date update script in case cathook's building steps have changed. Next, "updater.sh" will update all github repos and compile and install them using …
> Streamline cathook update process

- src/visual/menu/ncc/Menu.cpp
this was recently removed from the features list so its best to remove it from the menu too
> deleted heal arrows from menu

- include/hacks/AntiCheat.hpp
- src/hacks/AntiCheat.cpp
- src/hacks/ac/aimbot.cpp
- src/hacks/ac/antiaim.cpp
- src/visual/EffectGlow.cpp
- src/visual/menu/ncc/Menu.cpp
Correctly show friend glow first if health glow is enabled.
AC:
Add option to disable auto-rage (automatically set a target to rage if > x detections)
Add option to disable anti-aim check
> Display friend glow over health glow and add option to disable auto-rage and antiaim check

- src/visual/EffectChams.cpp
Avoids a crash if chams is not enabled
> Dont init chams if not necessary

- src/hooks/visual/PaintTraverse.cpp
Unless this has some other purpose I'm not aware of, it's useless code which only breaks WTS and requires hud_reloadscheme to fix.
> Fix WTS not working after map change

- install-all
Some users, including myself, received 404 errors when running the install-all script on Arch. The problem for me was that I needed to sync the package databases before attempting to install lib32-glew.
This change won't affect anyone who installs with no issues already but will allow anyone with the problem to install properly without any manual intervention.
> Updated flags on pacman to sync package databases before installing deps

- src/hooks/GetFriendPersonaName.cpp
\r character creates long space that is detectable. \e on the other hand is fully invisible
> Improve Name stealer

- include/PlayerTools.hpp
- include/helpers.hpp
- include/reclasses/CTFPartyClient.hpp
- src/PlayerTools.cpp
- src/hack.cpp
- src/hacks/Aimbot.cpp
- src/hacks/AntiCheat.cpp
- src/hacks/AutoBackstab.cpp
- src/hacks/AutoDetonator.cpp
- src/hacks/AutoJoin.cpp
- src/hacks/AutoSticky.cpp
- src/hacks/CatBot.cpp
- src/hacks/ESP.cpp
- src/hacks/MiscAimbot.cpp
- src/hacks/NavBot.cpp
- src/hacks/Trigger.cpp
- src/hacks/ac/aimbot.cpp
- src/helpers.cpp
- src/hooks/GetFriendPersonaName.cpp
- src/hooks/Paint.cpp
- src/playerlist.cpp
- src/reclasses/CTFGCClientSystem.cpp
- src/reclasses/CTFPartyClient.cpp
- src/settings/SettingsIO.cpp
- src/tfmm.cpp
- src/votelogger.cpp
More changes than expected
Overview:
- Added rage vote kick. Set RAGE state to player who attempted to kick friendly player. Attempt to vote kick players with RAGE state (controllable with `votelogger.autovote.no.rage`). Works only when `votelogger.autovote.no` is set to `true`
- Fix kick reason being ignored in vote kick command
- Add various party related signatures
- Use SendPartyChat function instead of constructing `say_party` command (that involved hacky `;` symbol replacements) in src/votelogger.cpp
- Fix `\` symbol not saved in settings
- Fix reporting mechanism reporting players with no steamID
- Added cat_pl_add_id. Now instead of using unreliable cat_pl_save/cat_pl_load you can maintain cfg file with all cat_pl_add_id (worthwhile note: files produced with cat_pl_save when …
> Merge l0fg with master

- src/hacks/Misc.cpp
This patch re-adds the ability to load a custom item schema from `/opt/cathook/data/items_game.txt` using the command `cat_schema`
> Fix Custom Item Schema Loading

- data/menu/nullifiedcat/trigger/autobackstab.xml
- src/hacks/AutoBackstab.cpp
[I wanted this to be added a long time ago](https://github.com/nullworks/cathook/issues/651#issuecomment-449452131), but it never got added
Its just the doBacktrackStab() method, but the for angle loop removed (basically triggerbot, but the code is trash). I removed it since a lot of server mods ban you for doing a quick spin and it looks suspicious.
I dont expect this to be merged, since the code is just copy pasted (and it could be made better)
> Add legit backtrack to autobackstab

- include/bytepatch.hpp
- src/hacks/Misc.cpp
- BytePatch which would wrap over two or more pages no longer causes a crash
- The Scoreboard icons no longer crash the game (hotfix undone)
> Fixes to crashes

- data/menu/nullifiedcat/aimbot.xml
- data/menu/nullifiedcat/antiaim.xml
- data/menu/nullifiedcat/visuals/uicolors.xml
The UI Colors tab with the added options
Also changed Fake Lag and Spin Speed to be a slider along with moving some things around in the HvH tab for simplicity's sake.  
* Spin Speed min/max is -45 to 45 as above/below is quite literally just Random which is already an option.
* Fake Lag min/max is 0 to 14. Above 14 causes actual lag.
As well as making FOV Opacity and Slow Aimbot into sliders and moving some things to be more consistent.
* Slow Aimbot min/max is 0 to 30. More than 30 is just memeing and doesn't help you aim better at all, though I'd say 30 is already going into meme territory due to how slow it is.
> Added a few color options I forgot about + slight menu changes

- data/menu/nullifiedcat/visuals/world.xml
- include/core/netvars.hpp
- src/core/netvars.cpp
- src/hacks/CMakeLists.txt
- src/hacks/Ragdolls.cpp
This patch adds an option to change the way ragdolls look.
Video demo: https://youtu.be/9Ds83esfbKc
There is also an option to only modify ragdolls that are spawned from players that were killed by the local player. This is enabled by default.
Currently, it will only change the ragdoll style if it is not already set. If a ragdoll is already set to be a gib and you have the override set to a gold ragdoll, it will spawn as a gib. If people want, you could easily add an option to "force" the selected ragdoll style.
I tested this for about half an hour in casual and I found that it will _occasionally_ fail if the person you just killed was airborn. I don't know if this is an issue with the way I detect if the ragdoll belongs to a person the player just killed, or if it's a bug with the game.
> Add ragdoll style overrides

- data/menu/nullifiedcat/movement.xml
- data/menu/nullifiedcat/trigger/autosticky.xml
- src/hacks/AutoSticky.cpp
- src/hacks/Bunnyhop.cpp
Two features that I thought were missing are a chance option to bhopping and a maximize sticky damage option. Bhop chance is the percent likelihood that a bhop succeeds. By default, auto sticky makes stickies blow up when someone is 130 hammer units away, which limited their damage in my play testing. This new option reduces the trigger radius to 80 hammer units, so they do more damage.
> Bhop chance and maximize sticky damage

- src/hacks/KillfeedColor.cpp
> Fix KillfeedColor not compiling with Stream safety

- data/menu/nullifiedcat/trigger/autopyro.xml
- src/hacks/AutoReflect.cpp
Mostly just modified IsEntStickyBomb and places where it's referenced to fit other projectiles. Feel like a lot of this could probably be made way more efficient, but it works I suppose
Created in response to #862
> AutoReflect support for toggling several different projectile types

- data/menu/nullifiedcat/visuals/esp.xml
- src/hacks/AutoDeadringer.cpp
- src/hacks/ESP.cpp
Adding the request of [#341 ](https://github.com/nullworks/cathook/issues/341) Adds two healthbar modes in addition to the already existing vertical. There is horizontal at the top of the esp and at the bottom.
> Added horizontal healthbars

- data/menu/nullifiedcat/aimbot.xml
- data/menu/nullifiedcat/visuals/esp.xml
- data/menu/nullifiedcat/visuals/radar.xml
- src/hacks/Aimbot.cpp
- src/hacks/ESP.cpp
- src/hacks/Radar.cpp
This Pull Request:
-fixes bone ESP and adds an option to color it according to player state
-adds an "assist only" option to aimbot that makes it only active if the mouse has moved in the last half second. This is useful for playing legit.
-adds a radar option for team buildings
Also, the bytepatch for keeping the sniper rifle breaks the command `zoom_sensitivity_ratio`
> Fixed Bone ESP and More

- src/hacks/AntiAntiAim.cpp
abuses the ~20deg area of hitbox that the head can be in while bruteforcing, to cover wider ranges than +90/-90
> very small edit to bruteforce angles

- include/bytepatch.hpp
- src/hacks/BulletTracers.cpp
- src/hacks/KillfeedColor.cpp
Make bullet traces only init when used, and make killfeed color be off by default, also rework bytepatch to do all the searching logic at patch time instead of construction.
> Bytepatch Fixes

- src/core/logging.cpp
Cppcheck detected several easy to fix errors
```
[src/core/logging.cpp:70]: (error) va_list 'list' was opened but not closed by va_end().
[src/core/logging.cpp:89]: (error) va_list 'list' was opened but not closed by va_end().
```
> Fix errors with va_list reported by cppcheck

- scripts/dependencycheck
- src/visual/drawing.cpp
- src/visual/fidgetspinner.cpp
Ubuntu 20.04 also inevitably has no support for libglez. Tested on Kubuntu 20.04 and on the Ubuntu 18.04 docker container.
> Add ubuntu 20.04 support

- scripts/dependencycheck
Adds CH_DEPENDENCYCHECK_FORCEYES which makes the dependencycheck script assume user consent.
> Fix cathook-gui on ubuntu 20.04

- src/hooks/CreateMove.cpp
This simply moves bSendPackets to CreateMoveEarly to make it more reliable, some people seem to have issues with it in CreateMove.
> Fix some reported issues with bSendPackets

- src/navparser.cpp
We crouchjump properly now too.
> Ignore "no jump" areas and improve jump logic

- .gitlab-ci.yml
- CMakeLists.txt
- include/config.h.in
- report-crash
- scripts/binarypackage/attach
- scripts/binarypackage/install
- scripts/binarypackage/readme
- src/pathio.cpp
The next cathook-gui update will re-enable binary mode! This lays the foundation and auto builds the binary mode packages every time stable is updated.
Also requesting permission to backport to stable for obvious reasons.
> Autobuild binary mode packages

- src/hacks/Warp.cpp
Sometimes you can get hit by someone who is dormant/invalid or the event is so delayed that it arrives once you/your target are dead, this aims to fix that crash (obversed on the bots of a hoster)
> Fix a crash caused by warp on hit

- scripts/dependencycheck
Emerge freaks out and refuses to install dependencies if -a is asked in a script. Removing it should fix the issues
> Fixed dependencies on gentoo

- install-data
https://t.me/nullworks/430473
https://unix.stackexchange.com/questions/498125/rsync-progress-parameter-syntax-error
> Remove --progress from rsync flags

- src/helpers.cpp
Changed UniformRandomInt and RandFloatRange to not depend on rand(), because this can cause little to no randomness depending on system.
> Make randoms not depend on rand()

- src/hacks/Aimbot.cpp
- src/helpers.cpp
Render bounds stretch under the floor for some reason, and apparently those npcs do have proper hitboxes we can aim at, so do it
^this is what it tried to aim at before, which occasionally (especially on teleporters) lead to alot of issues. It now aims at the middle most hitbox, which also makes aiming at sentries more reliable.
> Fix aiming at buildings

- src/helpers.cpp
Soooo apparently the hitboxes are invalid on dormant entities... oops. (No changes in aimbot needed, as aimbot never aims at dormant ents)
> Fix building aim

- src/hooks/SendNetMsg.cpp
This will make cathook only send auth packets when
1. Someone else sent one first
2. We are in textmode (we are a bot)
This was added to prevent external cheats from taking advantage of cathook's auth features without returning the favour and to prevent cathook users from landing on bot blacklists.
> Make cathook identify-neutral by default

- include/settings/Bool.hpp
- include/settings/Float.hpp
- include/settings/Int.hpp
- include/settings/Key.hpp
- include/settings/Manager.hpp
- include/settings/Registered.hpp
- include/settings/Rgba.hpp
- include/settings/Settings.hpp
- include/settings/String.hpp
- src/hack.cpp
- src/hacks/Misc.cpp
- src/hacks/Radar.cpp
- src/settings/Manager.cpp
- src/settings/Registered.cpp
This only affects the "Key" type because of SDL
Incorrect default variables means that all keys will be unbound as soon as a config file is loaded.
This PR essentially replaces e9b9cf16b17f0f42d14e80c97a6bf2577a730228
>  Fix: Fix default variable values being set incorrectly when preloading 

- install-data
Fixes a bug where `make install` would install to `/opt/cathook` regardless of what the the CMake var `DataPath` was set to.
> Install data to "DataPath" as intended

- src/hacks/AutoItem.cpp
- src/hooks/visual/DrawModelExecute.cpp
Autoitem would not work with '-1' because it would try to get the item.
Chams would still apply local player cham with teammates on and local player off.
> Fix a autoitem and a chams bug

- .gitmodules
- CMakeLists.txt
- data/menu/nullifiedcat/weapons/aimbot.xml
- src/hacks/Aimbot.cpp
1. Ubuntu 18.04 users are rarer than ever before. Not worth it to keep deprecated software around. Cathook will still work for them, it will just compile slower.
2. Projectile silent was removed at the request of @BenCat07
> Remove cotire & projectile silent

- src/core/sharedobj.cpp
replaced the formatted string with a string literal for "/proc/self/maps" since it maps to the same thing
> get memory map without finding our pid first

- data/menu/nullifiedcat/movement.xml
- include/navparser.hpp
- src/hacks/NavBot.cpp
This doesn't just add the melee mode variable, it also adds a full melee AI that will kick in whenever a bot is using a melee weapon. This could easily be used to make bots counter fist of steal heavies for example, by simply making the bot switch to melee in getBestSlot.
> Add melee mode to navbot

- src/visual/EffectGlow.cpp
Before there was no way to have glow for teammates and enemy buildings but not team buildings. Also, I can recreate the config UI if you are interested.
> Make teammate buildings option work correctly

- include/core/interfaces.hpp
- src/core/interfaces.cpp
- src/hacks/NavBot.cpp
- src/navparser.cpp
- Fixes patrol getting stuck because it walks to area closest to localplayer causing it to walk between a couple nodes for a long time.
- Makes patrol stay nearby the enemy objective on payload and control points
> Improve navbot patrol

- include/bytepatch.hpp
- src/hacks/BulletTracers.cpp
- src/hacks/Misc.cpp
Alot of hardware seems to not care about the memory being non readable, but some does, which can cause crashes that cannot really be reproduced. This PR simply marks those memory sections RWX before doing anything to ensure it works.
> Fix crashes with bytepatches on specific hardware due to memory being marked non readable

- CMakeLists.txt
This may or may not solve binary mode issues for some users.
> Build -march=x86-64 in binary mode

- src/hacks/Aimbot.cpp
This fixes the changes from #1306 that broke the assistance only option. Without this pull request, assistance only completely breaks the aimbot when enabled.
> Fix Assistance Only

- data/menu/nullifiedcat/visuals/world.xml
- include/sdk/HUD.h
- src/hooks/visual/OverrideView.cpp
- src/sdk/HUD.cpp
Just add a way to zoom in without a sniper scope, useful if you want to shoot someone from far away with a projectile for example, or just to check out what's going on in that direction.
> Add zoom key

- src/hacks/Misc.cpp
patches zoom check in CTFWearable::ShouldDraw()
```
// don't draw cosmetic while sniper is zoom
if ( pOwner == C_TFPlayer::GetLocalTFPlayer() && pOwner->m_Shared.InCond( TF_COND_ZOOMED ) )
return false;
````
> See cosmetics while zooming

- data/menu/nullifiedcat/visuals/chams.xml
- data/menu/nullifiedcat/visuals/glow.xml
- src/hooks/visual/DrawModelExecute.cpp
- src/visual/EffectGlow.cpp
This pull request allows the coloring of the aimbot's target (set in Visuals:Colors) to be disabled for chams and glow.
> Aimbot coloring option

- install-data
I don't think I need to explain why having **world** executable, writable, and readable permissions from any user is extremely unsafe and you would be fired for doing that at any job.
As far as I know, there is not another user that needs to interact with those directories that isn't the current one you're launching Steam, playing TF2, and compiling cathook from. While I would set it to world 0, I'm not 100% confident any other user may need to read this directory, and usually the umask for most standard systems is 002 so we'll just take the world writable out.
Lots and lots of servers dedicated to cathook bots currently suffer from this flaw if an unprivileged user has access to their system.
The directory in question is `/opt/cathook/data`
> Set secure directory permissions for cathook data directory

- src/ipc.cpp
> Update cathook for new boost mutex in IPC

- scripts/dependencycheck
Arch uses curl to download gdb binary, submitting crash reports use curl, and migrations use curl. I've found curl to not be installed by default usually.
> Add curl to dependency lists

- src/hacks/NavBot.cpp
Signed-off-by: Ashley <ash@trapacid.dev>
Partially solves https://github.com/nullworks/cathook/issues/1375
TFCond_Healing applies to any sort of gradual healing.
> Do not steal medpacks if being healed

- .gitignore
- include/hacks/AntiAim.hpp
- src/hacks/AntiAim.cpp
- src/hooks/SendNetMsg.cpp
This ignores any `.cache/*` files clangd creates, and stops the anti-aim from enabling 2 ticks after the grappling hook has been used, this has been tested and it is working.
> #701 fix & gitignore changes

- src/hacks/Aimbot.cpp
for some reason i thought "yeah backtrack == rapidfire"
> stop being an idiot and actually fix the snapping

- src/hacks/AutoBackstab.cpp
Literally just the title. Break out of the autobackstab loop after finding a valid entity instead of trying to backstab every single one of them.
> Fix autobackstab searching for targets even after a valid one was found

- src/hacks/AutoHeal.cpp
I noticed when the current healing target goes out of sight, CanHeal() returns false.
Add a check to return true if the target is already healing.
> Fix CanHeal() for already healing targets

- data/menu/nullifiedcat/antiaim.xml
- src/hacks/AntiAim.cpp
This pull request addresses a multitude of issues and complaints related to the functionality of Anti-aim in cathook. Previously you were not able to independently set fake and real angles for both pitch and yaw angles - this has now been solved with the creation of `antiaim.pitch.fake`, `antiaim.pitch.real`, `antiaim.yaw.fake` and `antiaim.yaw.real` with the additional static/custom values that can be set to each angle. 
I've been unable to test if fake yaw angles are working due to them not being visible in local servers (if that is what's happening), so I ask if anyone else could test them and determine that they're good to go for merging. I also apologize if the tab formatting looks different in GitHub, both Featherpad and Geany do that on my end.
> Add better Anti-aim options to HvH menu

- src/hacks/Aimbot.cpp
Self explanatory I guess. I initially attempted to rewrite the BestHitbox function so that it would return a vector of the desired position so that projectiles could aim at better spots (adjusted entity origin for feet aim), however I couldn't get it to stop aiming at the head so I felt like modifying the current function would be good enough for now. I might revisit this soon and properly do it if I feel like the current feet aim is not good enough.
I've also lowered the initial preferred hitbox to spine_3, due to weapons such as the Flare Gun simply missing the target by shooting above it (more directly related to projectile gravity prediction but this mitigates it well enough). The whole "aim to feet if target is grounded" portion was simplified and the Direct Hit will also do this as …
> Improve Auto hitbox positioning

- src/hacks/Aimbot.cpp
- src/prediction.cpp
- src/velocity.cpp
This will probably need some testing first.
We use engine prediction to get properly accurate simulations and avoid the hassle of replicating prediction ourselves.
To use Strafe prediction, the user will have to switch back to "normal" prediction instead.
> Switch back to engine prediction and make it work properly

- src/hacks/Radar.cpp
only really affects us if we spawn an object via console
> Fix crashes with radar when object team is -1

- src/hacks/AutoJoin.cpp
if we do it like this no more crash logs from autojoin
> Quit tf2 without causing a crash

- src/hacks/Aimbot.cpp
- src/prediction.cpp
After sitting down and taking some time to figure out how does the step prediction figure out the best target position, I realized that the method of calculating delta time, responsible for setting the new best position, could be wrong in specific scenarios when the target is moving away from the origin. Inverting it would fix the majority of those cases, however very slight edge cases would require the old ordering, so the higher value out of both variables is now the one being subtracted.
Another correction done was reordering the Auto hitbox scan for projectile weapons - sometimes the preferred hitbox would not be available and the cheat would scan the first available hitbox from top to bottom. This has now changed from bottom to top, since there is a larger chance of hitting the …
> Fix projectile aimbot aiming at wrong places

- .github/ISSUE_TEMPLATE/bug-report.md
Since the config file is now a requested item, we no longer need to ask the user for just literal screenshot of their menu in order to see what they have enabled.
Config is very useful as there may be other modules that can cause a crash when used in combination with another module. Removed "you can remove this line", making it a requirement.
Combined "drag and drop" information together, since it goes hand-in-hand. Made separate information in it's own separate block.
Please replace "paste symbolize-crash-log here instead" with "paste symbolize-crash-log here as well" if both symbolize-crash-log and logs are requested.
As always, "Allow edits by maintainers" has been specifically enabled. If something is not to your liking, you are fully allowed to modify any text to your own accord …
> Removed redundant request for screenshot of settings, and some other information clarity.

- src/hacks/AntiCheatBypass.cpp
it wasn't checking ones with the prefix
https://github.com/sapphonie/StAC-tf2/blob/bb2dd2b856d049ca35c9084c9e6abace2c60e40b/scripting/stac/stac_cvar_checks.sp#L40
> fix hiding of cat_ cvars from server
