src/gui/ncc/Menu.cpp
src/hacks/Aimbot.cpp
src/hacks/Bunnyhop.cpp
src/hacks/Misc.cpp

I added no-push, Its better than just managing cvars and makes it easier for the user to configure.
I don't know how good my "code" is but it works and does what its supposed to do without issues (that I know of)
Also, bhop will occasionally stop working while going up steep slopes so i changed 20 to 5 to make it try to jump more quickly after a jump. I've tested it and haven't had any problems since.

Added cool features

---

src/gui/ncc/Menu.cpp
src/hacks/Aimbot.cpp

Just as the title says. Check thru it so see if u like it. This is perfect with triggerbot for some spicy legit play. The  speed algorithm needs some work but this is working so why change it lol.
I also removed the dead code for the autoshoot delay, It would have been nice it it worked but Ill just remove it and try to fix it some other time.

Slow Aim Update + Remove broken code

---

src/gui/ncc/Menu.cpp
src/hacks/AntiAim.cpp

I've created a simple edge anti-aim from scratch ;)

Added Edge Anti-aim

---

README.md
TODO
attach
attach-backtrace
detach
install-resources.sh
makefile
reattach
res/convert.sh
update

I may have trampled over your tab settings, Will change it back if you want.

Nitpicking

---

src/hacks/AutoSticky.cpp

Before it was random but now it works perfect!

Improved auto-sticky vis check

---

src/gui/ncc/Menu.cpp
src/hacks/LagExploit.cpp

Added more control over lagexploit

---

README.md

With this added, users won't need to "find gcc6 on your own".

Added gcc6 installation script for Arch.

---

README.md

Added multiple periods, spellchecks, removed redundancies, made some topics more clear, spellcheck, etc etc.

Spellcheck & better explanations.

---

src/hacks/LagExploit.cpp

@Retarded-Skid fixed up infinite_healthpacks and added ammo compatibility, renaming the module to infinite_packs. 
Then someone overwrote it.
So, this is adding it back.

(Re-)added ammo packs to lag exploit

---

data/menu.json
src/colors.cpp
src/cvwrapper.cpp
src/cvwrapper.h
src/hacks/ESP.cpp

Sightline Changes + Colors

---

src/drawmgr.cpp

It's a simple change that allows you to change http://i.imgur.com/h6e6WrK.png to http://i.imgur.com/XtS8JGj.png
I think it's a nice option to have because running the game at a lower resolution can result in a lot of clutter from the info.

Added cat_info_min

---

src/hacks/FollowBot.cpp

literallyj ust fixs the idle timer

Fix followbot not jumping at all

---

src/hacks/LagExploit.cpp

- Fix cat_se_do
- Fix infinite pickups
- Add instant cloak/decloak (slight delay before being able to instant decloak again)
- Added instant rev up (slight delay before being able to instant rev up again)

Fixes + additions

---

src/hacks/LagExploit.cpp

- Fix Stickyspam
- Undo the command number and lastoutgoingcommand increase
- Add Loose Cannon Spam
- Fix not being able to doublestab with the knife if cloak is on

Important Updates:

---

src/hacks/LagExploit.cpp

- Added "cart farm mode"
- fixed some code

Additions:

---

check-data
include/hacks/ESP.hpp
include/macros.hpp
src/hacks/ESP.cpp

Fix Emoji Esp

---

src/sdk/checksum_md5.cpp

Apparently everyone has b1g gay for not doing that like fucking forever ago

b1g gayness removal

---

preload.sh

Fix preload.sh if you use steam runtime

---

README.md

cmake couldn't find SimpleIPC ¯\_(ツ)_/¯
#400

and simple-ipc

---

attach-backtrace-scramble.sh
class_dumping/generate-class-headers.js
class_dumping/generate-dummy-header.js
class_dumping/generate-dynamic-header.js
src/crits.cpp

Quotations, dupes, and camelCase

---

README.md

Made instructions 100% more clear.

---

include/hacks/Radar.hpp
include/hacks/hacklist.hpp
include/hooks/HookedMethods.hpp

Textmode fix

---

.gitmodules

Update .gitmodules and remove pointless subprojects

---

include/hacks/ESP.hpp
src/hacks/ESP.cpp
src/visual/menu/ncc/Menu.cpp

3D box ESP

---

TODO
include/conditions.hpp
include/helpers.hpp
include/localplayer.hpp
src/hacks/Aimbot.cpp
src/helpers.cpp
src/localplayer.cpp
src/visual/menu/ncc/Menu.cpp

1. Stop aiming while holding a PDA or the sapper.
2. Add option to stop automatically shooting if disguised while autoshoot is enabled.
3. Make wait for charge optional for the ambassador.
4. Clean up TODO list.

Do some stuff from todo list and clean it up

---

src/hacks/ESP.cpp
update

Use all available threads for update, update submodules and fix #493

---

src/core/cvwrapper.cpp
src/hacks/AutoDeadringer.cpp
src/hacks/ESP.cpp
src/hacks/FollowBot.cpp
src/visual/menu/ncc/ItemVariable.cpp

- Check if std::string pointer is nullptr
- Add Health option to deadringer
- add Auto jump on stuck followbot
- make ESP out vector static to avoid crashes

FIx some of the random crashes

---

src/hacks/KillSay.cpp
src/hacks/Spam.cpp
src/hooks/CreateMove.cpp
src/hooks/DispatchUserMessage.cpp
src/visual/EffectGlow.cpp

Cat_ucccccp_encrypt and cat_ucccccp_decrypt will still use type a but also decrypt both a and b.

UCCCCCP Type B only, no double spam and small changes

---

install-all
src/hacks/Aimbot.cpp
src/hacks/AutoBackstab.cpp
src/hacks/Backtrack.cpp
src/hacks/Trigger.cpp

Fix Backtrack not recognizing non-melee weapons correctly

---

src/navparser.cpp

Fix spy bots setting off stuck prevention

---

include/navparser.hpp
include/settings/Settings.hpp
src/hooks/CreateMove.cpp
src/navparser.cpp
src/visual/drawmgr.cpp

Navparser and pathing improvements

---

src/hacks/KillSay.cpp
src/votelogger.cpp

> experimental: [cat] votekick called: Jerry Seinfeld => Mr. Lean 2.O (#TF_vote_kick_player_other)
> sulfix: kick called by Jerry Seinfeld
also fixed possible crash on killsay.

votekick print to party chat.

---

.circleci/config.yml

Switch to arch

---

src/hack.cpp

Duped include statements in the same file.

Removed duplicate includes in hack.cpp

---

data/dominatesay.txt
include/hacks/CMakeLists.txt
include/hacks/DominateSay.hpp
include/hacks/hacklist.hpp
src/hack.cpp
src/hacks/CMakeLists.txt
src/hacks/DominateSay.cpp

"todo - Chat and Related - dominatesay"
totally did not copypaste killsay

DominateSay

---

install-all

Change install script to check if pacman exists

---

CMakeLists.txt
include/config.h.in
include/hacks/hacklist.hpp
src/hack.cpp
src/hacks/AutoJoin.cpp
src/hacks/CMakeLists.txt
src/hacks/Misc.cpp
src/hooks/CreateMove.cpp
src/hooks/DispatchUserMessage.cpp
src/hooks/LevelInit.cpp
src/hooks/LevelShutdown.cpp
src/hooks/Paint.cpp
src/hooks/SendDatagram.cpp
src/hooks/visual/FrameStageNotify.cpp

Cleanup: LAG_BOT ifdefs and CMake option

---

update

Fix an echo that wasnt printing in color

---

data/menu/nullifiedcat/visuals/glow.xml
include/visual/EffectGlow.hpp
src/visual/EffectGlow.cpp

flat glow instead of soft /shrug looks nicer
also fixed self rainbow glow not working and powerups not being toggleable

game glow cathook edition

---

src/visual/drawing.cpp

Make worldtoscreen great again

---

README.md
data/spam.txt

Fixes https://github.com/nullworks/catbot-setup/issues/22

Remove discord from spam

---

src/MiscTemporary.cpp
src/hack.cpp

This is not done yet as i am still fixing some other related if statements

Fix the visuals stuff being used wron

---

src/MiscTemporary.cpp
src/hack.cpp

Revert "Fix the visuals stuff being used wron"

---

include/config.h.in
include/hooks/HookedMethods.hpp
include/ipc.hpp
include/playerlist.hpp
src/entityhitboxcache.cpp
src/hack.cpp
src/hacks/AutoHeal.cpp
src/hacks/FollowBot.cpp
src/hooks/Paint.cpp
src/hooks/nographics.cpp
src/ipc.cpp
src/playerlist.cpp
src/tfmm.cpp
src/visual/menu/GuiInterface.cpp

For details, view commit descriptions.

Followbot and state system changes

---

data/menu/nullifiedcat/misc/catbot.xml
include/core/offsets.hpp
include/hacks/CatBot.hpp
include/hooks.hpp
include/hooks/HookedMethods.hpp
include/soundcache.hpp
src/hack.cpp
src/hacks/CatBot.cpp
src/hooks.cpp
src/hooks/CMakeLists.txt
src/hooks/EmitSound.cpp
src/hooks/nographics.cpp
src/soundcache.cpp
src/votelogger.cpp

Some Soundcache and bot updates

---

attach
attach-gdb
attach-libnamed.sh

Allow PID param

---

attach
attach-gdb
attach-libnamed.sh
src/hacks/Misc.cpp

Hotfix: Remove scoreboard color

---

data/menu/nullifiedcat/misc/collective.xml
src/hacks/Misc.cpp
src/hacks/SkinChanger.cpp
src/hooks/CreateMove.cpp
src/settings/SettingsIO.cpp

Cyoa PDA patch will not affect gameplay besides you being able to open the cyoa pda while taunting. Pretty much Useless as server doesn't let you play the animation.

Fixes & Improvements

---

.gitmodules
data/menu/nullifiedcat/antiaim.xml
include/hacks/Backtrack.hpp
include/helpers.hpp
include/navparser.hpp
include/textfile.hpp
src/hacks/Achievement.cpp
src/hacks/Aimbot.cpp
src/hacks/AntiAim.cpp
src/hacks/AutoHeal.cpp
src/hacks/Backtrack.cpp
src/hacks/BulletTracers.cpp
src/hacks/NavBot.cpp
src/hacks/Spam.cpp
src/helpers.cpp
src/hooks/SendDatagram.cpp
src/ipc.cpp
src/navparser.cpp
src/textfile.cpp
src/trace.cpp

Changes were tested with @BenCat07 in casual.

Merge HWGS and other changes

---

src/hack.cpp
src/hooks/Paint.cpp
src/hooks/visual/SDL_GL_SwapWindow.cpp
src/tfmm.cpp

Fix no visual builds not compiling

---

config
install-all
scripts/developer
scripts/migrations
scripts/updater

- Added migration to fix a CoTiRe error
- Add code to sync submodules if in non developer mode
- Don't run migrations in developer mode
- Update the developer script

Script updates

---

include/settings/Key.hpp

Fix #847 not working as intended

---

CONTRIBUTING.md
data/menu/nullifiedcat/movement.xml
include/core/logging.hpp
include/settings/SettingCommands.hpp
include/settings/SettingsIO.hpp
scripts/updater
src/core/logging.cpp
src/hacks/Aimbot.cpp
src/hacks/FollowBot.cpp
src/hacks/Misc.cpp
src/hacks/NavBot.cpp
src/settings/SettingCommands.cpp
src/settings/SettingsIO.cpp
src/visual/EffectGlow.cpp

Fixes #208 
Fixes #802 
Fixes #536 
Testing:

Various issue fixes

---

data/menu/nullifiedcat/visuals.xml
data/menu/nullifiedcat/visuals/uicolors.xml

UI Colors tab

---

src/entityhitboxcache.cpp
src/hacks/Aimbot.cpp
src/hacks/AntiAntiAim.cpp
src/hooks/visual/IN_KeyEvent.cpp
src/visual/EffectChams.cpp
src/visual/EffectGlow.cpp

- Improve aimbot accuracy in pseudo textmode
- Decrease time until revdown
- match pitchHook with yawHook in AntiAntiAim.cpp
- Remove dead code
- Fix #881 
- Reset github repository last updated date
- Updated localization files

Fix various small issues

---

data/menu/nullifiedcat/misc/catbot.xml
src/hacks/Achievement.cpp
src/hacks/Noisemaker.cpp

* Add Auto Noisemaker Equip (in Catbot Tab)
* Add Noisemaker spam to Catbot Tab

Noisemaker Additions

---

include/copypasted/CSignature.h
include/core/sharedobj.hpp
src/copypasted/CSignature.cpp
src/core/sharedobj.cpp
src/hooks/nographics.cpp
src/reclasses/CTFPartyClient.cpp
src/reclasses/C_MannVsMachineStats.cpp

This caused catbots to crash. No idea why it stopped working as i can find it fine manually in engine.so

Fix signature

---

include/MiscTemporary.hpp
src/ipc.cpp

Fix catbot crashing and wrong use of hooks

---

install-all
scripts/dependencycheck
scripts/updater
update

Preparation for Cathook GUI, since the user can't type in the password.

Allow custom sudo command via env vars

---

data/menu/nullifiedcat/visuals/glow.xml
src/visual/EffectGlow.cpp

I found this option useful. Do you want to add it to the master?

Adds option to glow to ignore disguised spies

---

data/menu/nullifiedcat/movement.xml
src/hacks/NavBot.cpp

These changes are to be merged asap as they break catbots in a way

Basic simple-ipc and navbot fixes

---

README.md
scripts/dependencycheck
scripts/updater

Fixes bugs and update readme with link to new install guide using GUI.

Add requirements for cathook gui

---

data/menu/nullifiedcat/aimbot.xml
data/menu/nullifiedcat/antiaim.xml
data/menu/nullifiedcat/chat.xml
data/menu/nullifiedcat/crits.xml
data/menu/nullifiedcat/debug.xml
data/menu/nullifiedcat/hackinfo.xml
data/menu/nullifiedcat/misc/anticheat.xml
data/menu/nullifiedcat/misc/autoload.xml
data/menu/nullifiedcat/misc/catbot.xml
data/menu/nullifiedcat/misc/collective.xml
data/menu/nullifiedcat/misc/spyalert.xml
data/menu/nullifiedcat/trigger/autodeadringer.xml
data/menu/nullifiedcat/trigger/autoheal.xml
data/menu/nullifiedcat/trigger/autosticky.xml
data/menu/nullifiedcat/triggerbot.xml
data/menu/nullifiedcat/visuals/bullettracers.xml
data/menu/nullifiedcat/visuals/chams.xml
data/menu/nullifiedcat/visuals/dominatemark.xml
data/menu/nullifiedcat/visuals/esp.xml
data/menu/nullifiedcat/visuals/glow.xml
data/menu/nullifiedcat/visuals/playerinfo.xml
data/menu/nullifiedcat/visuals/radar.xml
data/menu/nullifiedcat/visuals/tracers.xml
data/menu/nullifiedcat/visuals/ui.xml
data/menu/nullifiedcat/visuals/uicolors.xml
data/menu/nullifiedcat/visuals/world.xml

It always bothered me that much of the capitalization throughout the main window was wrong. I went through all the tabs and fixed it.

Fixed Menu Capitalization

---

data/menu/nullifiedcat/movement.xml
data/menu/nullifiedcat/trigger/autoheal.xml
data/menu/nullifiedcat/visuals/chams.xml
src/visual/EffectChams.cpp
src/visual/EffectGlow.cpp

The capitalization of movement.xml and autoheal.xml have been fixed. Also, there is an option for ignore disguised in chams

Fix movement.xml and add disguised option to chams

---

data/menu/nullifiedcat/visuals/radar.xml
data/menu/nullifiedcat/visuals/world.xml
src/hacks/Radar.cpp
src/hacks/Thirdperson.cpp

This is LightPower392. I think making a new account is the easiest way to create a second fork. This adds two options to thirdperson: it adds a keybind and allows you to auto disable it when zoomed. It also lets you use a circle radar. 
Also, I am working on adding the skinchanger to the UI if you want to see it.

Thirdperson and Radar Options

---

src/hacks/Noisemaker.cpp

Allow noise maker spam when dead

---

data/menu/nullifiedcat/aimbot.xml
data/menu/nullifiedcat/misc/autoequip.xml
include/MiscTemporary.hpp
include/hooks/GetFriendPersonaName.hpp
src/PlayerTools.cpp
src/hacks/Achievement.cpp
src/hacks/Aimbot.cpp
src/hacks/Backtrack.cpp
src/hacks/CatBot.cpp
src/hacks/FollowBot.cpp
src/hacks/Misc.cpp
src/hacks/NavBot.cpp
src/hacks/SkinChanger.cpp
src/hooks/others.cpp
src/hooks/visual/PaintTraverse.cpp
src/ipc.cpp
src/navparser.cpp
src/prediction.cpp

* Tapfire for miniguns
~* Improve backtrack~
* Readd rockettimeping to Projectile aimbot
* Add a way to equip stock items with autoequip (Especially useful on Engineer bots)
* Fix ArgC misuse
* Fix simple-ipc not being set up properly
* Fix some Engineer bot issues
* Improve Pathing when in sentry range
* Improve betrayal system

Various fixes and some improvements

---

.gitmodules
CMakeLists.txt
scripts/dependencycheck

Also install the latest cmake if it's too old on ubuntu.

Download boost if it's out of date

---

data/menu/nullifiedcat/aimbot.xml
data/menu/nullifiedcat/antiaim.xml
data/menu/nullifiedcat/chat.xml
data/menu/nullifiedcat/crits.xml
data/menu/nullifiedcat/misc.xml
data/menu/nullifiedcat/misc/announcer.xml
data/menu/nullifiedcat/misc/collective.xml
data/menu/nullifiedcat/movement.xml
data/menu/nullifiedcat/trigger/autoheal.xml
data/menu/nullifiedcat/trigger/autosticky.xml
data/menu/nullifiedcat/triggerbot.xml
data/menu/nullifiedcat/visuals.xml
data/menu/nullifiedcat/visuals/chams.xml
data/menu/nullifiedcat/visuals/dominatemark.xml
data/menu/nullifiedcat/visuals/playerinfo.xml
data/menu/nullifiedcat/visuals/radar.xml
data/menu/nullifiedcat/visuals/tracers.xml
data/menu/nullifiedcat/visuals/ui.xml
include/visual/menu/menu/Tooltip.hpp
src/visual/menu/menu/BaseMenuObject.cpp
src/visual/menu/menu/objects/Tooltip.cpp
src/visual/menu/menu/objects/container/Container.cpp

Tooltip fixes are mine, full credit for XML changes to @LightPower392.

Fix and add tooltips

---

include/PlayerTools.hpp
include/helpers.hpp
src/PlayerTools.cpp
src/hacks/Aimbot.cpp
src/hacks/ESP.cpp
src/hacks/Trigger.cpp
src/helpers.cpp

just a minor thing that bugged me before

Add more vaccinator autoshoot checks and ESP details

---

data/menu/nullifiedcat/movement.xml
include/hacks/Warp.hpp
include/helpers.hpp
include/hooks/HookedMethods.hpp
src/hacks/AutoBackstab.cpp
src/hacks/CMakeLists.txt
src/hacks/KillfeedColor.cpp
src/hacks/Radar.cpp
src/hacks/Warp.cpp
src/helpers.cpp
src/hooks/SendNetMsg.cpp
src/visual/menu/menu/wm/WindowCloseButton.cpp

Seems i also accidentally formatted stuff but i'm leaving it in here

Add a Warp hack

---

data/menu/nullifiedcat/aimbot.xml
include/helpers.hpp
include/reclasses/C_TFWeaponBase.hpp
src/CMakeLists.txt
src/helpers.cpp
src/nospread.cpp
src/sdk/CMakeLists.txt
src/sdk/checksum_crc.cpp

Does as it says. Only for projectiles though (Until we find a way to crack the server seed and or float time)

Add NoSpread

---

src/hacks/Exploits.cpp
src/nullnexus.cpp
src/visual/menu/menu/objects/TabButton.cpp

This includes some high priority fixes that should be fast tracked to stable ASAP.

Nullnexus temp deadlock and off by one error fixes

---

src/hacks/Aimbot.cpp

this needs to be merged ASAP for catbots

Fix textmode issues

---

data/menu/nullifiedcat/movement.xml
include/reclasses/CTFPlayerShared.hpp
src/hacks/MiscAimbot.cpp
src/hacks/Warp.cpp

- Fix issue with charge in jump and active charge
- Add A demoknight mode

Warp changes

---

attach
attach-gdb
attach-libnamed.sh
report-crash

Also add function names and unwind inlines

Sentry.io: Ask user if they want to submit crash logs on attach, improve addr2line accuracy

---

include/core/offsets.hpp
include/hooks/HookTools.hpp
include/hooks/HookedMethods.hpp
src/crits.cpp
src/hack.cpp
src/hacks/ESP.cpp
src/hooks/CreateMove.cpp

Fix potential crashes and confusing naming Scheme

---

data/menu/nullifiedcat/aimbot.xml
data/menu/nullifiedcat/misc/collective.xml
src/hacks/Misc.cpp

Interface for setting cl_cmdrate to -1 so I don't have to type it in console every time.

Interface for "Ping Reducer"

---

data/menu/nullifiedcat/crits.xml
include/crits.hpp
include/hacks/MiscAimbot.hpp
include/reclasses/CTFPlayerShared.hpp
src/crits.cpp
src/hacks/KillfeedColor.cpp
src/hacks/MiscAimbot.cpp
src/hacks/Warp.cpp
src/hooks/GetUserCmd.cpp
src/nospread.cpp

but not really because who needs it

rip old mode, and warp demoknight improvements

---

data/menu/nullifiedcat/chat.xml
src/settings/SettingsIO.cpp
src/votelogger.cpp

Also added migrations for other variables.

Log votes to [Cat] chat by default instead of party chat

---

include/DetourHook.hpp
include/bytepatch.hpp
src/hacks/MiscAimbot.cpp

Also removes memprotect spam and adds a detourhook class

Fix Demoknight detach crash

---

src/crits.cpp

Repurposed pull request. now Fixes a bug with minigun Crit multiplier

Fix Crithack Calculations on minigun

---

src/hacks/MiscAimbot.cpp

Don't globally increase mouse sensitivity

---

data/menu/nullifiedcat/aimbot.xml
include/localplayer.hpp
src/hacks/Aimbot.cpp
src/localplayer.cpp
src/nospread.cpp

Add option to disable aimbot if being spectated

---

src/hooks/CreateMove.cpp

Crithack apparently broke it, so this is a fix to that.

Fix bSendPackets not working (and undefined behaviour)

---

include/crits.hpp
src/crits.cpp
src/nospread.cpp

Cache the crit cmds for every weapon idx instead, and yes it does work this way even if you switch classes

Prevent Weapon Switch lag with crithack

---

data/menu/nullifiedcat/visuals/world.xml
src/hacks/Misc.cpp
src/hooks/visual/FrameStageNotify.cpp

This commit first of all fixes nightmode, then second of all makes it more customizeable, and the third point is that it fixes antiafk
Note: There is currently a bug where it will spam your console if you change settings, this is avoidable through some game interfering methods, so i am waiting for feedback from @TotallyNotElite on this matter.

Fix and improve nightmode (see description)

---

data/menu/nullifiedcat/antiaim.xml
data/menu/nullifiedcat/movement.xml
include/conditions.hpp
include/reclasses/C_TFWeaponBaseMelee.hpp
include/sdk/netmessage.hpp
src/hacks/Misc.cpp
src/hacks/Warp.cpp
src/sdk/netmessage.cpp

- Add a speed meter
- Smoothen Warp Drastically
- GIve full control while in warp (Especially useful for bots)
- Rewrite the peek mode
- Add 22 tick fakelag (as a sideeffect)
- Fix our netmessages all being wrong (sad)
haha cl_move hook go brrr

Alot of warp related stuff (see description)

---

scripts/dependencycheck
scripts/updater

Not great, but better than it was.

Gentoo support & improvements to the dependencycheck script

---

src/hitrate.cpp

i somehow missed this. We seriously need to remake cathook so this is not even possible to do

fix hitrate event

---

data/menu/nullifiedcat/antiaim.xml
data/menu/nullifiedcat/chat.xml
data/menu/nullifiedcat/crits.xml
data/menu/nullifiedcat/debug.xml
data/menu/nullifiedcat/hackinfo.xml
data/menu/nullifiedcat/misc/anticheat.xml
data/menu/nullifiedcat/misc/autoequip.xml
data/menu/nullifiedcat/misc/autoload.xml
data/menu/nullifiedcat/misc/buildings.xml
data/menu/nullifiedcat/misc/catbot.xml
data/menu/nullifiedcat/misc/collective.xml
data/menu/nullifiedcat/misc/datacenters.xml
data/menu/nullifiedcat/misc/spyalert.xml
data/menu/nullifiedcat/movement.xml
data/menu/nullifiedcat/trigger/autoheal.xml
data/menu/nullifiedcat/trigger/autopyro.xml
data/menu/nullifiedcat/trigger/autospy.xml
data/menu/nullifiedcat/trigger/autosticky.xml
data/menu/nullifiedcat/triggerbot.xml
data/menu/nullifiedcat/visuals/bullettracers.xml
data/menu/nullifiedcat/visuals/chams.xml
data/menu/nullifiedcat/visuals/esp.xml
data/menu/nullifiedcat/visuals/glow.xml
data/menu/nullifiedcat/visuals/playerinfo.xml
data/menu/nullifiedcat/visuals/radar.xml
data/menu/nullifiedcat/visuals/tracers.xml
data/menu/nullifiedcat/visuals/ui.xml
data/menu/nullifiedcat/visuals/uicolors.xml

This is sentence case localization for the current version of Cathook.

Sentence Case

---

include/core/netvars.hpp
include/helpers.hpp
include/reclasses/C_BaseAnimating.hpp
include/reclasses/C_BasePlayer.hpp
include/reclasses/reclasses.hpp
src/core/netvars.cpp
src/crits.cpp
src/entityhitboxcache.cpp
src/hacks/Aimbot.cpp
src/hacks/AntiAntiAim.cpp
src/helpers.cpp
src/hooks/DispatchUserMessage.cpp

This just has a few miscelanous improvements and fixes to existing things.
- Rework Slow aim (Previous one had major issues due to the way it worked
- Fix the Critmeter Text not being properly alligned
- Improve The chat censor filter
- Fix desyncs with crithack

Misc improvements

---

include/helpers.hpp
src/entityhitboxcache.cpp
src/hacks/Aimbot.cpp
src/hacks/AutoBackstab.cpp
src/hacks/AutoReflect.cpp
src/hacks/MiscAimbot.cpp
src/hacks/Trigger.cpp
src/helpers.cpp
src/hooks/CreateMove.cpp
src/hooks/visual/FrameStageNotify.cpp

Fix hitbox interpolation and fix punch angles in aiming functions

---

src/hacks/Aimbot.cpp

this is why i should not use old code

Check preferred hitbox first in aimbot with backtrack

---

src/hacks/KillfeedColor.cpp
src/hacks/Misc.cpp

Scoreboard fix

---

src/hacks/Misc.cpp

This just sends the server your cmdrate instead of setting it clientside

Fix the ping reducer changing clientside cmdrate

---

data/menu/nullifiedcat/visuals/world.xml
include/core/netvars.hpp
src/core/netvars.cpp
src/hacks/AutoBackstab.cpp
src/hacks/ESP.cpp
src/hacks/Misc.cpp
src/trace.cpp

The Contracker entirerly breaks animations, so i fixed that. Alongside that i also made melee traces use the proper mode and make snipers able to shoot through teammates.

Fix issues related to traces and Contracker

---

.gitmodules
README.md
scripts/migrations

Obviously still keeping our anti repository deletion stuff around in case something similar happens again.

Move back to github

---

src/hooks/visual/FrameStageNotify.cpp

This also fixes a more common crash on config load

Only change color if it has changed in nightmode settings

---

src/hacks/Aimbot.cpp

Fix out of bounds iteration in backtrack aimbot

---

include/MiscTemporary.hpp
src/hooks/CreateMove.cpp
src/hooks/SendNetMsg.cpp

This method can be spammed as much as we want which means we can send it like every 30 seconds instead of having to wait, also means bots can instantly reply to any auth

Use a better and faster method of authentication

---

src/crits.cpp

Command to make executing this exploit work 100% of the time: alias doubleattack "+attack;+attack2;wait 5;-attack;-attack2"
Video demonstration: https://t.me/nullworks/411869

Add crithack support for the engineer double attack exploit

---

src/itemtypes.cpp

This is the first time this happened to me :shrug:

Itemtypes.cpp: Fix crash when model is nullptr

---

src/hack.cpp

just make the popup not appear lol

""Fix"" locale issue caused by steam

---

src/hooks/nographics.cpp

- Fully null Material Swap buffers
- Make map loading times shorter and take less cpu time by skipping ressource checks
- Remove CViewRender::Render calls from game
- Remove a sleep(15000) that gets used on instances marked as "textmode"

Improve textmode performance

---

src/localplayer.cpp

Add Cowmangler as projectile weapon

---

data/menu/nullifiedcat/trigger/autoheal.xml
include/MiscTemporary.hpp
include/hacks/Aimbot.hpp
include/hacks/MiscAimbot.hpp
include/hacks/NavBot.hpp
src/MiscTemporary.cpp
src/hacks/Aimbot.cpp
src/hacks/AutoHeal.cpp
src/hacks/MiscAimbot.cpp
src/hacks/NavBot.cpp
src/navparser.cpp

This was supposed to be a 2 line fix...

Add autoheal.look-at-path, fix some bad code, create a unified DoSlowAim

---

data/menu/nullifiedcat/aimbot.xml
data/menu/nullifiedcat/misc/collective.xml
data/menu/nullifiedcat/trigger/autoheal.xml
include/core/offsets.hpp
include/helpers.hpp
include/prediction.hpp
src/hacks/Aimbot.cpp
src/hacks/AutoBackstab.cpp
src/hacks/AutoHeal.cpp
src/hacks/Backtrack.cpp
src/hacks/Misc.cpp
src/hacks/MiscAimbot.cpp
src/helpers.cpp
src/prediction.cpp
src/tfmm.cpp

Closes #535, Closes #939, Closes #894, Closes #996, Closes #1117 and a crash in backtrack.
Additionally, some projectile weapons have also been fixed

Alot of small fixes and improvements

---

src/localplayer.cpp

Why is the sapper not using the sapper weapon class, this makes no sense.

Add sapper as pda

---

include/MiscTemporary.hpp
src/hacks/AutoItem.cpp
src/hooks/CreateMove.cpp
src/hooks/SendNetMsg.cpp

Money worm
Money worm
This is not tested, if you accept this and it doesn't work it's your fault.
Money worm
@aUniqueUser is the MVP

Fix: Autoitem: Use maps instead of looping thru achivement items

---

data/menu/nullifiedcat/aimbot.xml
data/menu/nullifiedcat/triggerbot.xml
src/hacks/ESP.cpp

This is mostly a slimmed down version of my previous attempt, please mr TNE I only want the ESP to not yell at me ![](https://cdn.discordapp.com/emojis/600712155632762915.png)

Readability improvement take #2

---

data/menu/nullified-ui.xml
data/menu/nullifiedcat/movement.xml
data/menu/nullifiedcat/trigger/autoheal.xml
data/menu/nullifiedcat/warp.xml
include/core/offsets.hpp
include/hacks/Warp.hpp
include/helpers.hpp
include/hooks/HookTools.hpp
include/hooks/HookedMethods.hpp
include/prediction.hpp
src/crits.cpp
src/hack.cpp
src/hacks/Warp.cpp
src/helpers.cpp
src/hooks/CreateMove.cpp
src/prediction.cpp

I guess i somehow made it work?

Add Rapidfire

---

src/hacks/ESP.cpp
src/hacks/Misc.cpp

Taunting is for people like me who has the tauntfix (https://t.me/tauntfix_reborn) mod installed, what that mod does in simple words are removing taunting animations at an attempt of making hitboxes match with server

Revving and taunting condition esp

---

include/helpers.hpp
src/hacks/Aimbot.cpp
src/hacks/AutoBackstab.cpp
src/hacks/Trigger.cpp
src/helpers.cpp

This is a fix for https://github.com/nullworks/cathook/issues/1116

Stealth spell counts as being cloaked

---

include/core/netvars.hpp
src/core/netvars.cpp
src/hacks/ESP.cpp

Added building condition esp

---

src/hacks/DominateSay.cpp

Saw a comment asking for new dominate says, well here ya go.

new default dominate says

---

include/DetourHook.hpp
include/WeaponData.hpp
include/hacks/AutoJoin.hpp
include/hacks/ChatCommands.hpp
include/hacks/ESP.hpp
include/hacks/FollowBot.hpp
include/hacks/Misc.hpp
include/hacks/Spam.hpp
include/hacks/UberSpam.hpp
include/nospread.hpp
include/sconvars.hpp
src/hacks/ESP.cpp

This should cut used performance down to ~1/10 in my testing

Fix: Esp performance improvements

---

include/hacks/ESP.hpp
src/hacks/ESP.cpp

Fix ESP bugs

---

data/menu/nullifiedcat/misc/autoitem.xml

Improve in-game autoitem documentation

---

src/hacks/AntiAim.cpp

Fix antiaim bug

---

include/core/interfaces.hpp
include/core/sdk.hpp
src/core/interfaces.cpp
src/hacks/ESP.cpp

Uses localization for weapon esp (#TF_Weapon_Minigun => Minigun)

Localize ESP weapon strings

---

src/hacks/CatBot.cpp
src/hacks/ESP.cpp
src/ipc.cpp
src/prediction.cpp

This caused crashes on 32 player servers

Fix incorrect usage of g_GlobalVars->maxClients

---

src/hacks/NavBot.cpp

to make that spycrab dude shut the fuck up

fix best weapon

---

src/hacks/AntiDisguise.cpp

Should fix this shit https://www.youtube.com/watch?v=Lm1CEFjhg8g

Make remove disguise true for textmode bots by default

---

data/menu/nullifiedcat/visuals/radar.xml
include/conditions.hpp
src/hacks/ESP.cpp
src/hacks/Misc.cpp
src/hacks/Radar.cpp
src/helpers.cpp
src/localplayer.cpp
src/visual/drawing.cpp

- Added the new conditions to the cheat
- Added "gassed" condition esp
- Added an option to make radar's outer border and targeted players border color change color to target color if aimbot is targeting someone
- Added more weapons to related list
- Changed projectile speed data to tf2wiki ones and de-duped it
- Changed case on powerup esp
- Changed font to Verdana

More stuff

---

src/hacks/Misc.cpp

Remove stealth kill patch that causes crashes for some users

---

src/hacks/AutoBackstab.cpp

I added 2 of the suggestion https://github.com/nullworks/cathook/issues/735#issuecomment-503894644 provided.

canFaceStab changes

---

src/hacks/Misc.cpp

Reverts nullworks/cathook#1340

Revert "Remove stealth kill patch that causes crashes for some users"

---

attach
scripts/dependencycheck

[Old PR](https://github.com/nullworks/cathook/pull/1342)
(I don't use git that much :P)

Check if attach is ran as root + Add Debian support to dependencycheck script 

---

src/prediction.cpp

Fix rare prediction crash

---

code-style.md

Because I've felt confused when I first read this.

Add a preposition before "new"

---

src/hacks/Warp.cpp

Fix a crash inside warp on hit

---

README.md

If the matrix room ever gets to be public again, please remember to change this readme

Fixed typo and added matrix room choice in readme

---

src/hooks/nographics.cpp
src/textmode.cpp

Only affects specific hardware but still a pain in the ass.

Fix more textmode memory write crashes

---

data/menu/nullifiedcat/weapons/triggerbot.xml
include/reclasses/C_TFWeaponBaseMelee.hpp
src/hacks/AutoBackstab.cpp

Also adds melee range modifier to melees

Improve autobackstab by using the swing trace provided by tf2

---

data/menu/nullifiedcat/weapons/triggerbot.xml
src/hacks/AutoReflect.cpp

Closes https://github.com/nullworks/cathook/issues/760

Auto extinguish and code cleanup

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/suggestion.md

Edit whatever you want to change first, don't @ me

Added my own bug/feature templates

---

include/core/sharedobj.hpp
src/core/sharedobj.cpp
src/hack.cpp

(petition to) remove sourcelock

---

data/menu/nullifiedcat/antiaim.xml
data/menu/nullifiedcat/crits.xml
data/menu/nullifiedcat/misc/autoparty.xml
data/menu/nullifiedcat/misc/spyalert.xml
data/menu/nullifiedcat/movement.xml
data/menu/nullifiedcat/visuals/chams.xml
data/menu/nullifiedcat/visuals/chamshaders.xml
data/menu/nullifiedcat/visuals/colors.xml
data/menu/nullifiedcat/visuals/esp.xml
data/menu/nullifiedcat/visuals/glow.xml
data/menu/nullifiedcat/visuals/ui.xml
data/menu/nullifiedcat/visuals/world.xml
data/menu/nullifiedcat/weapons/aimbot.xml
data/menu/nullifiedcat/weapons/nospread.xml
data/menu/nullifiedcat/weapons/triggerbot.xml
src/hacks/AutoSticky.cpp

This renames the autosticky's legit mode to semi-legit and creates a new legit mode that also requires a line of sight with the enemy, in addition to what semi-legit already does. This also adds more tooltips.

Extra Autosticky Option + More Tooltips

---

.gitignore
include/hacks/AntiAim.hpp
src/hacks/AntiAim.cpp
src/hooks/SendNetMsg.cpp

"Fixes anti aim with grappling hook, removes clangd meme includes, adds clangd .cache to .gitignore"

squash your shit.

---

src/prediction.cpp

This pull request removes the circle logic applied for air->ground transition.
Also fixes a couple of bugs that make strafe prediction on local player impossible, and uses the proper velocity to determine if a player is moving or not

Remove strafeprediction for grounded players

---

src/hacks/KillfeedColor.cpp

This drastically reduces code complexity, and also makes it actually maintainable. Names also now get colored seperately.

Rewrite Killfeed Color code

---

include/hacks/Aimbot.hpp
src/hacks/Aimbot.cpp
src/hacks/Warp.cpp

Found this out because a user without aimkey sent me his config, i did not think about this possibility.

Fix problems with targets going out of aimbot range with rapidfire

---

data/menu/nullifiedcat/visuals/world.xml
include/MiscTemporary.hpp
include/common.hpp
src/hooks/visual/OverrideView.cpp

Solves https://github.com/nullworks/cathook/issues/1427 and https://github.com/nullworks/cathook/issues/958
Signed-off-by: Ashley <ash@trapacid.dev>

Zoom sensitivity ratio tweak, header file modifications

---

src/hacks/Aimbot.cpp

Aimbot shoots burning and cloak flicker spies.

---

src/hacks/Warp.cpp

Added Thermal Thruster to ignore

Add the thermal thruster to ignored weapons in rapidfire

---

src/hacks/Warp.cpp

Improves upon and Closes #1456

Fix some issues with the tick window in rapidfire

---

data/menu/nullifiedcat/weapons/aimbot.xml
include/core/netvars.hpp
include/enums.hpp
include/hacks/Backtrack.hpp
include/hacks/Trigger.hpp
include/reclasses/C_BaseEntity.hpp
src/core/netvars.cpp
src/crits.cpp
src/entityhitboxcache.cpp
src/hacks/Aimbot.cpp
src/hacks/AutoBackstab.cpp
src/hacks/Backtrack.cpp
src/hacks/MiscAimbot.cpp
src/hacks/Trigger.cpp
src/hooks/visual/DrawModelExecute.cpp

Increases hitrate immensely, also aims to lower code complexity (for modules like aimbot and triggerbot) and does "proper" backtracking, aka teleporting the entity back to where they were originally

Rewrite backtrack

---

src/hacks/Aimbot.cpp

Just a QOL and performance change.

Make aimbot not run unneccesarily when in rapidfire

---

src/hacks/Warp.cpp
src/navparser.cpp

Fixes two small things:
- Demoknight charge sometimes immediately charging at someone again even when warp is empty
- Bots getting stuck on buildings (Closes #1450)

Small Bugfixes

---

data/menu/nullifiedcat/visuals/esp.xml
src/hacks/HeadESP.cpp

I noticed that the esp.xml used by BenCat was missing features like the head ESP and box corner sizes.

ESP XML + Head ESP

---

src/hacks/BulletTracers.cpp
src/hacks/ESP.cpp
src/hacks/Misc.cpp

These were later reported, and fixed after way too much work (for a singular byte)

Fix more crashes

---

src/nospread.cpp
src/prediction.cpp

Fix an issue with nospread
fix a crash with projectile prediction

Add two small fixes

---

include/core/netvars.hpp
src/core/netvars.cpp
src/crits.cpp
src/hacks/Aimbot.cpp
src/helpers.cpp
src/prediction.cpp

- Huntsman Aimbot now properly aims, works with CanShoot on or off, and with AutoShoot disabled
- Pills are now properly aimed
- Crossbow now targets teammates if they are missing health
- Prediction now no longer passes through walls or gets stuck on janky static prop hitboxes
- Make The Loose cannon work with aimbot and crithack

Add a ton of projectile prediction improvements

---

include/reclasses/C_BasePlayer.hpp
src/hacks/MiscAimbot.cpp
src/hooks/Shutdown.cpp

Just fixes Charge aim and random names not working in menu

Small fixes

---

src/hooks/visual/OverrideView.cpp

They were switched for some reason

Fix  zoom sensitivity ratio tweak

---

src/hacks/Warp.cpp

Only affects us if we have a null weapon
also fixes t-pose crashes

Fix crash with invalid weapons

---

config_data/startup_sounds.txt
src/visual/drawing.cpp

Add in startup sounds

---

data/menu/nullifiedcat/visuals/world.xml
data/menu/nullifiedcat/weapons/aimbot.xml
include/SetupBonesReconst.hpp
include/copypasted/CSignature.h
include/core/interfaces.hpp
include/core/netvars.hpp
include/core/sharedobj.hpp
include/entityhitboxcache.hpp
include/helpers.hpp
include/sdk/CServerTools.hpp
include/sdk/animationlayer.h
src/CMakeLists.txt
src/SetupBonesReconst.cpp
src/copypasted/CSignature.cpp
src/core/interfaces.cpp
src/core/netvars.cpp
src/core/sharedobj.cpp
src/entitycache.cpp
src/entityhitboxcache.cpp
src/hacks/Aimbot.cpp
src/helpers.cpp
src/hooks/CreateMove.cpp
src/hooks/PlayerAnimFix.cpp
src/sdk/CMakeLists.txt
src/sdk/CServerTools.cpp
src/sdk/basically_the_whole_mathlib.cpp
src/sdk/setup_bones.cpp
src/sdk/studio.cpp
src/sdk/utlsymbol.cpp
src/votelogger.cpp

Reconstruct Setupbones on the client so it more closely matches the server. Oh also, add a remove taunts option.

Rewrite Setupbones 

---

report-crash
src/crits.cpp
src/prediction.cpp
src/visual/EffectGlow.cpp

- Fix crithack bucket sometimes updating multiple times or not at all
- Fix glow always showing on powerups even with the corresponding option disabled
- Fix prediction causing massive lags
- Fix report-crash sometimes failing to report crashes and also update the report URL

Fix a bunch of issues

---

src/crits.cpp

Stickybomb launchers crithack fix

---

data/menu/nullifiedcat/visuals/uicolors.xml
src/hacks/Aimbot.cpp
src/hacks/AutoBackstab.cpp
src/hacks/AutoHeal.cpp
src/hacks/MiscAimbot.cpp
src/hooks/visual/DrawModelExecute.cpp
src/nospread.cpp

Fix autoheal issues with tf_medigun_autoheal 0/1
Show tooltip ui colors settings in menu
Fix projectile nospread not running
Fix Pop On Voice Command not running when Auto-Vaccinator is enabled
Fix autobackstab issue
Fix issues with DoSlowAim
Fix chams still running when visual.disable is true
Fix aimbot aiming at moving stickybombs

Fix some issues

---

src/hacks/Misc.cpp

fix for https://github.com/nullworks/cathook/issues/1634

fix for newest update

---

src/hacks/Aimbot.cpp

->Removed an unneeded debugging log that somehow got it
->Fixed bug where multiple entities would be rendered as current target with the chams aimbot thing
-> re-put in my melee aimbot fixes (They got removed from that branch somehow)

Fixed visuals

---

CMakeLists.txt
data/menu/nullifiedcat/weapons/aimbot.xml
include/helpers.hpp
src/hacks/Aimbot.cpp
src/helpers.cpp

-> Removed precompiled header check since CMAKE below 3.20 isn't supported anyway
--> Fixed menu 
-> Fixed potential small bug  if the hitbox was 17

Menu Fix+Small changes

---

src/hacks/Aimbot.cpp

Shortest distance priority mode got removed somehow

---

src/votelogger.cpp

Also not sure if it's not better to use "CountdownTimer" that uses "GlobalVars->curtime" I mean server time based timer but it works like this too

Better vote timer

---

src/hooks/LevelShutdown.cpp

Fixed textmode

---

src/hooks/PlayerAnimFix.cpp

Yep this wasn't checked for CE_GOOD so it led to a nullptr dereference

Player Anim Fix

---

include/itemtypes.hpp

Catbot uses this file for some reason, an include was missed.

itemtype include fix

---

include/entitycache.hpp
include/helpers.hpp
scripts/migrations
src/PlayerTools.cpp
src/entitycache.cpp
src/hacks/Aimbot.cpp
src/hacks/AntiAntiAim.cpp
src/hacks/AutoHeal.cpp
src/hacks/ESP.cpp
src/hacks/FollowBot.cpp
src/hacks/MiscPlayerInfo.cpp
src/hacks/Tracers.cpp
src/helpers.cpp
src/hitrate.cpp
src/hooks/GetFriendPersonaName.cpp
src/playerlist.cpp

Just moved GetPlayerInfo + ran format on Aimbot
Big improvements to arcing projectiles. Added a range check, and checked the actual arc of the projectile

Minor entitycache fix
